# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17phsBLkR1jepkL5zqMD3mfvCfjghmRov
"""



import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the dataset
df = pd.read_csv('Unemployment_data.csv')

# 2. Basic info
print(df.head())
print(df.info())

# 3. Clean the data
# Strip leading/trailing spaces from column names
df.columns = df.columns.str.strip()

# Convert 'Date' column to datetime with dayfirst=True
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

# Drop rows with NaT in 'Date' or any other missing values
df = df.dropna()

# Sort the DataFrame by the 'Date' column
df = df.sort_values(by='Date')

# Reset index after dropping rows
df.reset_index(drop=True, inplace=True)

# 4. Plot unemployment trend
plt.figure(figsize=(12, 6))
sns.lineplot(data=df, x='Date', y='Estimated Unemployment Rate (%)', hue='Region')  # Ensure 'Region' column exists
plt.title('Unemployment Rate Over Time')
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.legend(title='Region')
plt.grid(True)
plt.tight_layout()
plt.show()

# 5. Summary statistics
print(df.groupby('Region')['Estimated Unemployment Rate (%)'].describe())

# 6. Optional: Moving average trend
df['Unemployment MA'] = df.groupby('Region')['Estimated Unemployment Rate (%)'].transform(lambda x: x.rolling(window=3).mean())
plt.figure(figsize=(10, 5))
sns.lineplot(data=df, x='Date', y='Unemployment MA', hue='Region')
plt.title('3-Month Moving Average of Unemployment Rate')
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.legend(title='Region')
plt.grid(True)
plt.tight_layout()
plt.show()

"""NEW CODE

"""

